# Generated by Django 4.2.28 on 2026-05-13 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actionlog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='loginlog',
            table=None,
        ),
    ]
